<?php
//tag, homepage, tag, KSSWF, Lorem, Ipsum 

//keywords can be set-up for every page on line 2 in a comment!
//correct syntax is "//one, two, three, four, five, etc"
//if incorrect, or not set, the keywords will be default; default keywords are set in index.php
?>
<?php  
gen_bcnav(true,">");
?>
<hr/>
<br/>
<h1>Lorem Ipsum h1</h1>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Integer tempor. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Quisque porta. Integer vulputate sem a nibh rutrum consequat. Morbi scelerisque luctus velit. Nunc auctor. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Aliquam in lorem sit amet leo accumsan lacinia. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Nunc dapibus tortor vel mi dapibus sollicitudin. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Phasellus faucibus molestie nisl. Nulla non lectus sed nisl molestie malesuada. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor.</p>
<p>Nam sed tellus id magna elementum tincidunt. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. In rutrum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a nibh rutrum consequat. Nunc auctor. Etiam commodo dui eget wisi. Nunc dapibus tortor vel mi dapibus sollicitudin. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nulla quis diam. Vivamus luctus egestas leo. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim.</p>
<p>Nulla pulvinar eleifend sem. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Praesent in mauris eu tortor porttitor accumsan. Donec vitae arcu. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Nullam sit amet magna in magna gravida vehicula. Aenean vel massa quis mauris vehicula lacinia. Aliquam erat volutpat. Pellentesque pretium lectus id turpis. Duis risus.</p>
<h2>Lorem Ipsum h2</h2>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Integer tempor. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Quisque porta. Integer vulputate sem a nibh rutrum consequat. Morbi scelerisque luctus velit. Nunc auctor. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Aliquam in lorem sit amet leo accumsan lacinia. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Nunc dapibus tortor vel mi dapibus sollicitudin. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Phasellus faucibus molestie nisl. Nulla non lectus sed nisl molestie malesuada. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor.</p>
<p>Nam sed tellus id magna elementum tincidunt. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. In rutrum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a nibh rutrum consequat. Nunc auctor. Etiam commodo dui eget wisi. Nunc dapibus tortor vel mi dapibus sollicitudin. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nulla quis diam. Vivamus luctus egestas leo. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim.</p>
<h3>Ipsum Dolor h3</h3>
<p>Ipsum dolor sit amet, consectetuer adipiscing elit. Integer tempor. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Quisque porta. Integer vulputate sem a nibh rutrum consequat. Morbi scelerisque luctus velit. Nunc auctor. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Aliquam in lorem sit amet leo accumsan lacinia. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Nunc dapibus tortor vel mi dapibus sollicitudin. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Phasellus faucibus molestie nisl. Nulla non lectus sed nisl molestie malesuada. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor.</p>
<h4>Dolor Sit Amet h4</h4>
<p>Dolor sit amet, consectetuer adipiscing elit. Integer tempor. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Quisque porta. Integer vulputate sem a nibh rutrum consequat. Morbi scelerisque luctus velit. Nunc auctor. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Aliquam in lorem sit amet leo accumsan lacinia. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Nunc dapibus tortor vel mi dapibus sollicitudin. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Phasellus faucibus molestie nisl. Nulla non lectus sed nisl molestie malesuada. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor.</p>
<?php 
//generate HOME stuff like NEWS?
?>